services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: consma
      MYSQL_ROOT_PASSWORD: 1@Shashikant
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: smart-contact-manager
    ports:
      - "8085:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/consma
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1@Shashikant
    restart: on-failure

  nagios:
    image: jasonrivers/nagios:latest
    container_name: nagios
    ports:
      - "9086:80"
    environment:
      NAGIOSADMIN_USER: nagiosadmin
      NAGIOSADMIN_PASS: admin
    volumes:
      - ./nagios/etc:/opt/nagios/etc
      - ./nagios/var:/opt/nagios/var
    depends_on:
      - app
      - db
    restart: on-failure

volumes:
  db_data:
